[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/telegram/*"
  to = "/.netlify/functions/telegram-proxy"
  status = 200
  force = true
